'use client';
import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, BookOpen, CircleHelp, Cloud, ExternalLink, FileText, LockKeyhole, LogOut, Moon, Plane, RefreshCw, Save, ShieldCheck, Sun, UserPlus } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { SidebarProvider, Sidebar, SidebarHeader, SidebarContent, SidebarFooter, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarInset, SidebarTrigger } from '@/components/ui/sidebar';
import Questionnaire from '@/components/questionnaire';
import FormEditor from '@/components/form-editor';
import DocumentChecklist from '@/components/document-checklist';
import ReviewApplication from '@/components/review-application';
import { initialData, questionnaireErrors, familyLabel, routeDetail, sourcePaths, sourceWarnings, type ApplicationData, type AppRecord, type DocumentRecord } from '@/lib/application';

const stepLabels=['Find your application','Complete your form','Add documents','Review & submit'];
const cloneInitial=()=>structuredClone(initialData);
const parse=async(response:Response):Promise<any>=>response.json();
export default function Workspace({user,signInPath,chatGPTSignOutPath}:{user:{name:string;email:string;provider:'chatgpt'|'email'}|null;signInPath:string;chatGPTSignOutPath:string}){
 const [app,setApp]=useState<AppRecord|null>(null),[data,setData]=useState<ApplicationData>(cloneInitial),[documents,setDocuments]=useState<DocumentRecord[]>([]),[step,setStep]=useState(0),[question,setQuestion]=useState(0),[loading,setLoading]=useState(Boolean(user)),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[message,setMessage]=useState(''),[errors,setErrors]=useState<string[]>([]);
 const [theme,setTheme]=useState<'light'|'dark'>('light');
 useEffect(()=>{const saved=localStorage.getItem('airworthy-theme');const next=saved==='dark'||(saved!=='light'&&matchMedia('(prefers-color-scheme: dark)').matches)?'dark':'light';setTheme(next);document.documentElement.classList.toggle('dark',next==='dark');},[]);
 const toggleTheme=()=>setTheme(current=>{const next=current==='dark'?'light':'dark';document.documentElement.classList.toggle('dark',next==='dark');localStorage.setItem('airworthy-theme',next);return next;});
 const signOut=async()=>{if(user?.provider==='chatgpt'){window.location.assign(chatGPTSignOutPath);return;}await fetch('/api/auth/signout',{method:'POST'});window.location.reload();};
 useEffect(()=>{if(!user)return;let live=true;(async()=>{try{let r=await fetch('/api/application',{cache:'no-store'});let body=await parse(r);if(!r.ok)throw new Error(body.error);if(!body.application){r=await fetch('/api/application',{method:'POST'});body=await parse(r);if(!r.ok)throw new Error(body.error);}if(live){setApp(body.application);setData(body.application.data);setDocuments(body.documents||[]);setStep(body.application.step||0);}}catch(e){if(live)setErrors([e instanceof Error?e.message:'The workspace could not be loaded.']);}finally{if(live)setLoading(false);}})();return()=>{live=false};},[user]);
 const change=(next:ApplicationData)=>{setData(next);setDirty(true);setMessage('Unsaved changes');setErrors([])};
 const save=async(nextStep=step,nextData=data)=>{if(!app||app.status==='submitted')return true;setBusy(true);setErrors([]);try{const r=await fetch('/api/application',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:app.id,data:nextData,step:nextStep})});const body=await parse(r);if(!r.ok)throw new Error(body.error);setApp({...app,data:nextData,step:nextStep,updatedAt:body.updatedAt});setStep(nextStep);setDirty(false);setMessage('Draft saved');return true;}catch(e){setErrors([e instanceof Error?e.message:'The draft could not be saved.']);return false;}finally{setBusy(false)}};
 const handleQuestionnaire=async()=>{if(data.answers.goal==='replacement'){setQuestion(3);return;}const issue=questionnaireErrors(data.answers);if(issue.length){setErrors(issue);return;}await save(1);};
 const navigate=async(n:number)=>{if(n>0&&questionnaireErrors(data.answers).length){setStep(0);setQuestion(0);setErrors(['Complete the application questions before opening this step.']);return;}if(dirty&&!await save(n))return;setStep(n);setMessage('');setErrors([]);};
 const upload=async(requirementId:string,files:File[])=>{if(!app||!await save(2))return;setBusy(true);try{for(const file of files){const form=new FormData();form.set('applicationId',app.id);form.set('requirementId',requirementId);form.set('file',file);const r=await fetch('/api/documents',{method:'POST',body:form});const body=await parse(r);if(!r.ok)throw new Error(body.error);setDocuments(current=>[...current,body.document]);}setMessage('Document attached');}catch(e){setErrors([e instanceof Error?e.message:'The document could not be uploaded.']);}finally{setBusy(false)}};
 const remove=async(id:string)=>{setBusy(true);try{const r=await fetch(`/api/documents/${id}`,{method:'DELETE'});const body=await parse(r);if(!r.ok)throw new Error(body.error);setDocuments(current=>current.filter(d=>d.id!==id));setMessage('Document removed');}catch(e){setErrors([e instanceof Error?e.message:'The document could not be removed.']);}finally{setBusy(false)}};
 const download=async()=>{setBusy(true);setErrors([]);try{if(dirty&&!await save(step))return;const {buildDraftPdf,savePdf}=await import('@/lib/pdf-export');savePdf(await buildDraftPdf(data,documents));setMessage('PDF draft downloaded');}catch(e){setErrors([e instanceof Error?e.message:'The PDF draft could not be created.']);}finally{setBusy(false)}};
 const submit=async()=>{if(!app||!await save(3))return;setBusy(true);try{const r=await fetch('/api/submit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:app.id})});const body=await parse(r);if(!r.ok){setErrors(body.errors||[body.error]);return;}setApp({...app,status:'submitted',receipt:body.receipt,submittedAt:body.submittedAt,step:3});setStep(3);setMessage('Concept submission recorded');}catch(e){setErrors([e instanceof Error?e.message:'The concept submission could not be recorded.']);}finally{setBusy(false)}};
 const readOnly=app?.status==='submitted';const shownStep=Math.max(0,Math.min(step,3));
 return <SidebarProvider style={{'--sidebar-width':'18rem'} as React.CSSProperties}><Sidebar><SidebarHeader className="brand"><span className="brand-mark"><Plane size={25}/></span><div><strong>Airworthy</strong><span>APPLICATION WORKSPACE</span></div></SidebarHeader><SidebarContent className="nav-body"><span className="eyebrow side-label">YOUR APPLICATION</span><SidebarMenu>{stepLabels.map((label,i)=><SidebarMenuItem key={label}><SidebarMenuButton className="step-link" isActive={shownStep===i} onClick={()=>void navigate(i)} disabled={loading}><span className="step-number">{String(i+1).padStart(2,'0')}</span><span>{label}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="side-guide"><BookOpen/><h3>Source-grounded, with uncertainty visible.</h3><p>The form path and checklist cite the supplied FAA sources. Known gaps remain flagged for confirmation.</p><a href={sourcePaths.form} target="_blank" rel="noreferrer">FAA Form 8130-6 <ExternalLink/></a></div></SidebarContent><SidebarFooter className="account"><span className="avatar">{user?user.name.slice(0,1).toUpperCase():<LockKeyhole/>}</span><div><strong>{user?user.name:'Your private workspace'}</strong><span>{user?(user.provider==='chatgpt'?'ChatGPT account':'Email account'):'Sign in to save your progress'}</span></div>{user&&<button className="account-signout" onClick={()=>void signOut()} aria-label="Sign out" title="Sign out"><LogOut/></button>}</SidebarFooter></Sidebar>
 <SidebarInset><header className="topbar"><div><SidebarTrigger/><span>Airworthiness certification</span><span className="breadcrumb">/</span><strong>{familyLabel(data.answers)}</strong></div><div className="top-actions"><Button variant="outline" className="theme-toggle" onClick={toggleTheme} aria-label={`Use ${theme==='dark'?'light':'dark'} mode`} title={`Use ${theme==='dark'?'light':'dark'} mode`}>{theme==='dark'?<Sun/>:<Moon/>}<span>{theme==='dark'?'Light':'Dark'}</span></Button><span className="concept-tag"><span/> Concept workspace</span>{user&&app?.status!=='submitted'&&<Button variant="outline" disabled={!dirty||busy||loading} onClick={()=>void save()}>{busy?<RefreshCw className="spin"/>:<Save/>}{dirty?'Save draft':'Saved'}</Button>}</div></header><div className="page-wrap"><div className="page-title"><div className="eyebrow">STEP {String(shownStep+1).padStart(2,'0')} / {stepLabels[shownStep].toUpperCase()}</div><h1>{shownStep===0?'Tell us what you’re applying for.':shownStep===1?'Complete your Form 8130-6 draft.':shownStep===2?'Assemble your application documents.':'Check your application package.'}</h1><p>{shownStep===0?'A few questions select the applicant sections and supporting-document path.':shownStep===1?'Work through the applicable sections. Your answers remain editable until concept submission.':shownStep===2?'Attach application documents and prepare the records the FAA may review.':'Confirm the information, citations, and concept acknowledgment before recording it.'}</p></div>
 {message&&<div className="save-state" aria-live="polite"><Cloud/>{message}</div>}{errors.length>0&&<div className="global-errors" role="alert"><strong>Something needs attention</strong>{errors.map(e=><p key={e}>{e}</p>)}</div>}
 {!user?<Login signInPath={signInPath}/>:loading?<Loading/>:<div className="content-grid">{shownStep===0?(question===3?<Replacement onBack={()=>setQuestion(0)}/>:<Questionnaire answers={data.answers} onChange={a=>change({...data,answers:a,attest:false,consent:false})} question={question} onQuestion={setQuestion} onContinue={()=>void handleQuestionnaire()} busy={busy}/>):shownStep===1?<FormEditor data={data} onChange={change} onBack={()=>{setStep(0);setQuestion(0)}} onContinue={()=>void save(2)} onDownload={()=>void download()} busy={busy} readOnly={readOnly}/>:shownStep===2?<DocumentChecklist data={data} documents={documents} onUpload={upload} onRemove={remove} onContinue={()=>void save(3)} busy={busy} readOnly={readOnly}/>:<ReviewApplication data={data} documents={documents} onChange={change} onSubmit={()=>void submit()} onDownload={()=>void download()} busy={busy} status={app?.status||'draft'} receipt={app?.receipt} submittedAt={app?.submittedAt}/>}<SourcePanel data={data}/></div>}
 <footer className="page-footer"><span>Independent concept • Not an FAA service</span><span>Source-based guidance. Applicant and FAA review required.</span></footer></div></SidebarInset></SidebarProvider>;
}
function Login({signInPath}:{signInPath:string}){
 const [mode,setMode]=useState<'signin'|'signup'>('signin'),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[working,setWorking]=useState(false);
 const submit=async(event:React.FormEvent)=>{event.preventDefault();setWorking(true);setError('');try{const response=await fetch(`/api/auth/${mode}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,email,password})});const body=await parse(response);if(!response.ok)throw new Error(body.error);window.location.reload();}catch(reason){setError(reason instanceof Error?reason.message:'The account request could not be completed.');setWorking(false);}};
 return <div className="content-grid"><section className="work-card"><div className="card-heading"><span className="mini-icon">{mode==='signup'?<UserPlus/>:<LockKeyhole/>}</span><div><h2>{mode==='signup'?'Create your account':'Sign in to your workspace'}</h2><p>Your form and supporting documents stay together.</p></div></div><div className="login-content"><p>Use an email account for this workspace or continue with your ChatGPT credentials.</p><div className="auth-tabs" role="tablist" aria-label="Account action"><button type="button" role="tab" aria-selected={mode==='signin'} className={mode==='signin'?'active':''} onClick={()=>{setMode('signin');setError('')}}>Sign in</button><button type="button" role="tab" aria-selected={mode==='signup'} className={mode==='signup'?'active':''} onClick={()=>{setMode('signup');setError('')}}>Create account</button></div><form className="auth-form" onSubmit={submit}>{mode==='signup'&&<label><span>Name</span><input className="form-input" name="name" autoComplete="name" value={name} onChange={e=>setName(e.target.value)} required minLength={2} maxLength={80}/></label>}<label><span>Email</span><input className="form-input" type="email" name="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required maxLength={254}/></label><label><span>Password</span><input className="form-input" type="password" name="password" autoComplete={mode==='signup'?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)} required minLength={12} maxLength={128}/><small>{mode==='signup'?'Use 12 or more characters.':''}</small></label>{error&&<p className="auth-error" role="alert">{error}</p>}<button className="primary-link" disabled={working}>{working?<RefreshCw className="spin"/>:mode==='signup'?<UserPlus/>:<ArrowRight/>}{working?'Please wait':mode==='signup'?'Create account':'Sign in'}</button></form><div className="auth-divider"><span>or</span></div><a className="outline-auth" href={signInPath} target="_top">Continue with ChatGPT <ArrowRight/></a><p className="fine-text">This concept does not file an application with the FAA.</p></div></section><SourcePanel data={initialData}/></div>}
function Loading(){return <section className="work-card loading-card"><RefreshCw className="spin"/><h2>Opening your application</h2><p>Loading the latest saved draft and documents.</p></section>}
function Replacement({onBack}:{onBack:()=>void}){return <section className="work-card replacement-card"><div className="card-heading"><span className="mini-icon"><CircleHelp/></span><div><h2>Contact your local FAA office for a replacement.</h2><p>FAA Form 8130-6 is not required for a replacement airworthiness certificate.</p></div></div><div className="form-body"><div className="notice"><ShieldCheck/><p>AC 21-12D § 1.1 separates replacement certificates from original, recurrent, and amendment applications. FAA Order 8130.2M § 2-4 contains the issuing-office procedure.</p></div><ol><li>Identify the FAA office or authorized representative responsible for the aircraft.</li><li>Ask which replacement evidence and surrender actions apply to the circumstances.</li><li>Do not start a Form 8130-6 application for a replacement unless the FAA directs you to.</li></ol><a className="outline-link" href={`${sourcePaths.ac}#page=4`} target="_blank" rel="noreferrer">Open the source guidance <ExternalLink/></a></div><div className="card-actions"><Button variant="ghost" onClick={onBack}><ArrowLeft/> Change request</Button></div></section>}
function SourcePanel({data}:{data:ApplicationData}){const warnings=sourceWarnings(data.answers);return <aside className="context-panel"><div className="context-heading"><ShieldCheck/><span>SOURCE BASIS</span></div><h3>{data.answers.family?familyLabel(data.answers):'Three supplied FAA sources'}</h3><p>{data.answers.family?routeDetail(data.answers):'Form, applicant guidance, and certification procedures.'}</p><hr/>{[['8130-6','Application form',sourcePaths.form],['8130.2M','Certification procedures',sourcePaths.order],['21-12D','Applicant guidance',sourcePaths.ac]].map(([code,title,path])=><a className="source-item" key={code} href={path} target="_blank" rel="noreferrer"><span className="source-code">{code}</span><div><strong>{title}</strong><p>Open source PDF</p></div><ExternalLink/></a>)}{warnings.length>0&&<div className="context-note"><CircleHelp/><div><strong>Needs FAA confirmation</strong>{warnings.map(w=><p key={w}>{w}</p>)}</div></div>}<div className="context-note"><CircleHelp/><p>FAA review and inspection determine eligibility. Completing this concept does not establish airworthiness.</p></div></aside>}

