'use client';
import { useRef, useState } from 'react';
import { Check, Download, FileText, Upload, X, Info, ArrowRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { requirements, sourcePaths, type ApplicationData, type DocumentRecord } from '@/lib/application';
export default function DocumentChecklist({data,documents,onUpload,onRemove,onContinue,busy,readOnly}:{data:ApplicationData;documents:DocumentRecord[];onUpload:(id:string,files:File[])=>Promise<void>;onRemove:(id:string)=>void;onContinue:()=>void;busy:boolean;readOnly:boolean}){
 const list=requirements(data.answers);const [active,setActive]=useState<string|null>(null);const input=useRef<HTMLInputElement>(null);
 const upload=async(id:string,files:File[])=>{setActive(id);await onUpload(id,files);setActive(null);};
 return <section className="work-card"><div className="card-heading"><span className="mini-icon"><Upload size={21}/></span><div><h2>Your supporting documents</h2><p>{list.filter(r=>r.required).length} application document types · PDF, PNG, or JPG · up to 10 MB each</p></div></div><div className="document-intro"><div className="notice"><Info size={18}/><p>Use non-sensitive demonstration documents. Do not upload proprietary, confidential, export-controlled, or unrelated material. Source: AC 21-12D § 12.1.</p></div><p>“Application document” items are needed for this concept’s selected path. “Prepare for review” items are records to have available; upload them when requested. The FAA may ask for additional material.</p></div>
 <input className="sr-only" ref={input} type="file" aria-label="Upload supporting documents" accept="application/pdf,image/png,image/jpeg,.pdf,.png,.jpg,.jpeg" multiple onChange={e=>{const files=Array.from(e.target.files||[]);const id=input.current?.dataset.requirement;if(id&&files.length)void upload(id,files);e.target.value='';}}/>
 <div className="document-list">{list.map(r=>{const attached=documents.filter(d=>d.requirementId===r.id);return <article className="document-row" key={r.id}><div className={`doc-icon ${attached.length?'received':''}`}>{attached.length?<Check size={19}/>:<FileText size={19}/>}</div><div className="doc-main"><div className="doc-title"><h3>{r.title}</h3><span className={`doc-badge ${r.required?'required-badge':''}`}>{r.kind}</span></div><p>{r.detail}</p><a className="source-link" href={`${sourcePaths[r.doc]}#page=${r.page}`} target="_blank" rel="noreferrer">{r.source}</a>
 {attached.map(d=><div className="attached-file" key={d.id}><Check size={15}/><a href={`/api/documents/${d.id}`}>{d.name}</a><span>{d.size<1024*1024?`${Math.ceil(d.size/1024)} KB`:`${(d.size/1024/1024).toFixed(1)} MB`}</span><a href={`/api/documents/${d.id}`} aria-label={`Download ${d.name}`}><Download size={15}/></a>{!readOnly&&<button type="button" disabled={busy} onClick={()=>onRemove(d.id)} aria-label={`Remove ${d.name}`}><X size={15}/></button>}</div>)}</div>{!readOnly&&<Button variant="outline" className="upload-button" disabled={busy} onClick={()=>{if(input.current){input.current.dataset.requirement=r.id;input.current.click();}}}><Upload size={16}/>{active===r.id?'Uploading…':attached.length?'Add file':'Upload'}</Button>}</article>;})}</div>
 {documents.some(d=>!list.some(r=>r.id===d.requirementId))&&<div className="form-body"><h3>Files from an earlier path</h3><p className="fine-text">These remain saved but do not count toward the current checklist.</p>{documents.filter(d=>!list.some(r=>r.id===d.requirementId)).map(d=><div className="attached-file" key={d.id}><a href={`/api/documents/${d.id}`}>{d.name}</a>{!readOnly&&<button onClick={()=>onRemove(d.id)} aria-label={`Remove ${d.name}`}><X size={15}/></button>}</div>)}</div>}
 <div className="card-actions"><span>{documents.length} file{documents.length===1?'':'s'} attached</span><Button className="primary-button" disabled={busy} onClick={onContinue}>Review application <ArrowRight/></Button></div></section>;
}
