'use client';
import { useState } from 'react';
import { ArrowRight, Edit3, ExternalLink, FileDown, FileText, Info } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Fields } from './application-fields';
import { sections, familyLabel, routeDetail, sourcePaths, type ApplicationData } from '@/lib/application';
export default function FormEditor({data,onChange,onBack,onContinue,onDownload,busy,readOnly}:{data:ApplicationData;onChange:(d:ApplicationData)=>void;onBack:()=>void;onContinue:()=>void;onDownload:()=>void;busy:boolean;readOnly:boolean}){
 const list=sections(data.answers);const [tab,setTab]=useState(list[0]?.id||'II');const update=(key:string,value:string)=>onChange({...data,fields:{...data.fields,[key]:value},attest:false,consent:false});
 return <section className="work-card form-card"><div className="card-heading form-heading"><span className="mini-icon"><FileText size={21}/></span><div><h2>FAA Form 8130-6</h2><p>Applicant sections selected from AC 21-12D Table 1.</p></div><div className="heading-actions"><Button variant="outline" onClick={onDownload}><FileDown/> Download draft PDF</Button><a className="outline-link" href={sourcePaths.form} target="_blank" rel="noreferrer">Original form <ExternalLink size={15}/></a></div></div>
 <div className="route-band"><div><span>CERTIFICATE PATH</span><strong>{familyLabel(data.answers)}</strong><p>{routeDetail(data.answers)}</p></div><button onClick={onBack} disabled={readOnly}><Edit3/> Change answers</button></div>
 <Tabs value={tab} onValueChange={v=>setTab(String(v))} className="form-tabs"><TabsList variant="line" aria-label="Form sections" className="section-tabs">{list.map(s=><TabsTrigger key={s.id} value={s.id}>Section {s.id}</TabsTrigger>)}</TabsList>{list.map(s=><TabsContent key={s.id} value={s.id}><fieldset disabled={readOnly} className="section-fieldset"><div className="section-title"><div><span>SECTION {s.id}</span><h3>{s.title}</h3></div><a href={`${s.id==='I'?sourcePaths.ac:sourcePaths.ac}`} target="_blank" rel="noreferrer">{s.source} <ExternalLink/></a></div>{s.hint&&<div className="notice"><Info/><p>{s.hint}</p></div>}<Fields definitions={s.fields} values={data.fields} onChange={update} disabled={readOnly}/>{s.id==='II'&&<div className="form-only-note"><Info/><p>Sections V and VIII are for FAA or designee use. This workspace does not edit them.</p></div>}</fieldset></TabsContent>)}</Tabs>
 <div className="office-block"><h3>Submission routing</h3><p>Identify the FAA office you intend to select. The concept does not verify jurisdiction or send data to that office.</p><div className="field-grid"><Fields definitions={[{id:'faaOffice',label:'Intended FAA office',required:true,hint:'Office name or location.'},{id:'designee',label:'Requested designee',required:false,hint:'A request may be rejected or reassigned.'}]} values={data.fields} onChange={update} disabled={readOnly}/></div></div>
 <div className="card-actions"><span>{readOnly?'Submitted concept — read only':'Applicant entries save to your private draft.'}</span>{!readOnly&&<Button className="primary-button" disabled={busy} onClick={onContinue}>Save and add documents <ArrowRight/></Button>}</div></section>;
}
