'use client';
import { AlertTriangle, Check, CheckCircle2, Download, ExternalLink, FileDown, FileText, Plane, Send } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { CheckField } from './application-fields';
import { familyLabel, routeDetail, requirements, sections, sourcePaths, validationErrors, type ApplicationData, type DocumentRecord } from '@/lib/application';
export default function ReviewApplication({data,documents,onChange,onSubmit,onDownload,busy,status,receipt,submittedAt}:{data:ApplicationData;documents:DocumentRecord[];onChange:(d:ApplicationData)=>void;onSubmit:()=>void;onDownload:()=>void;busy:boolean;status:string;receipt?:string;submittedAt?:string}){
 const errors=validationErrors(data,documents);const requiredDocs=requirements(data.answers).filter(r=>r.required);const isSubmitted=status==='submitted';
 if(isSubmitted)return <section className="work-card confirmation"><div className="confirmation-icon"><CheckCircle2/></div><span className="eyebrow">CONCEPT SUBMISSION RECEIVED</span><h2>Your application package is saved.</h2><p>No application or documents were sent to the FAA. Use this workspace to retain the submitted concept and download its draft.</p><div className="receipt"><div><span>CONCEPT RECEIPT</span><strong>{receipt}</strong></div><div><span>RECORDED</span><strong>{submittedAt?new Date(submittedAt).toLocaleString():'—'}</strong></div></div><Button className="primary-button" onClick={onDownload}><FileDown/> Download Form 8130-6 draft</Button></section>;
 return <section className="work-card review-card"><div className="card-heading"><span className="mini-icon"><Send size={21}/></span><div><h2>Review your concept application</h2><p>Resolve incomplete items, then record your concept submission.</p></div></div><div className="review-summary"><div><span><Plane/> CERTIFICATE</span><h3>{familyLabel(data.answers)}</h3><p>{routeDetail(data.answers)}</p></div><div><span><FileText/> FORM</span><h3>{sections(data.answers).map(s=>s.id).join(', ')}</h3><p>Applicant sections included</p></div><div><span><Download/> DOCUMENTS</span><h3>{documents.length}</h3><p>{requiredDocs.filter(r=>documents.some(d=>d.requirementId===r.id)).length} of {requiredDocs.length} required types attached</p></div></div>
 {errors.length?<div className="review-errors" role="alert"><div><AlertTriangle/><h3>{errors.length} item{errors.length===1?'':'s'} to resolve</h3></div><ul>{errors.map(e=><li key={e}>{e}</li>)}</ul></div>:<div className="review-ready"><Check/><div><h3>Concept checks complete</h3><p>Your package is complete under the rules represented by the three supplied sources.</p></div></div>}
 <div className="review-details"><details open><summary>Application answers</summary><dl><div><dt>Request</dt><dd>{data.answers.goal}</dd></div><div><dt>Role</dt><dd>{data.answers.role}</dd></div><div><dt>Registration</dt><dd>{data.answers.registrationStatus}</dd></div><div><dt>Aircraft background</dt><dd>{data.answers.background}</dd></div></dl></details><details><summary>Attached documents ({documents.length})</summary>{documents.length?<ul className="review-files">{documents.map(d=><li key={d.id}><Check/><a href={`/api/documents/${d.id}`}>{d.name}</a></li>)}</ul>:<p>No documents attached.</p>}</details></div>
 <div className="attestations"><CheckField id="attest" checked={data.attest} onChange={v=>onChange({...data,attest:v})}><strong>I have reviewed the FAA Form 8130-6 certification statement.</strong><small>I understand that I am responsible for the accuracy of the application and the aircraft’s stated condition.</small></CheckField><CheckField id="consent" checked={data.consent} onChange={v=>onChange({...data,consent:v})}><strong>I consent to this concept electronic acknowledgment.</strong><small>This records an acknowledgment in the concept only. It is not an FAA AWC signature or submission.</small></CheckField></div>
 <div className="source-confirm"><a href={`${sourcePaths.ac}#page=33`} target="_blank" rel="noreferrer">AC 21-12D submission guidance <ExternalLink/></a></div><div className="card-actions"><Button variant="outline" onClick={onDownload}><FileDown/> Download draft PDF</Button><Button className="primary-button" disabled={busy||errors.length>0} onClick={onSubmit}>Record concept submission <Send/></Button></div></section>;
}
