import { PDFDocument, StandardFonts, rgb, type PDFForm, type PDFFont } from 'pdf-lib';
import { familyLabel, isFlight, isImport, requirements, routeDetail, sections, type ApplicationData, type DocumentRecord } from './application';
const checkboxMap:Record<string,string>={
 Standard:'Check Box3',Normal:'Check Box5',Utility:'Check Box6',Acrobatic:'Check Box7',Transport:'Check Box8',Commuter:'Check Box9',Balloon:'Check Box10','Standard Other':'Check Box11',Special:'Check Box4',Primary:'Check Box12','Light-sport':'Check Box13',Limited:'Check Box22',Provisional:'Check Box23','Class I':'Check Box24','Class II':'Check Box25',Restricted:'Check Box26',Experimental:'Check Box35','Special flight permit':'Check Box57',Multiple:'Check Box60',Retain:'Check Box59',Dealer:'Check Box61',Import:'Check Box1',TCDS:'Check Box62',AD:'Check Box64',STC:'Check Box63',Maintenance:'Check Box65',
 'Research and development':'Check Box42','Showing compliance with regulations':'Check Box40','Crew training':'Check Box44',Exhibition:'Check Box47','Air racing':'Check Box41','Market survey':'Check Box46','Amateur-built':'Check Box45','Primary category kit-built':'Check Box43','Former military aircraft':'Check Box39','Light-sport category kit-built':'Check Box38','Former light-sport category':'Check Box37',
 Agriculture:'Check Box30','Forest and wildlife conservation':'Check Box29','Aerial surveying':'Check Box32',Patrolling:'Check Box31','Weather control':'Check Box34','Aerial advertising':'Check Box33','Restricted Other':'Check Box28','Special operations':'Check Box27',
 'Ferry for repairs, alterations, maintenance, or storage':'Check Box56','Evacuate from impending danger':'Check Box55','Excess of maximum certificated takeoff weight':'Check Box54','Delivering or exporting':'Check Box53','Production flight testing':'Check Box58','Customer demonstration flights':'Check Box52',
};
const textMap:Record<string,string>={registration:'1. REGISTRATION MARK',builder:'2. AIRCRAFT MANUFACTURE\'s or BUILDER’S NAME',model:'3. AIRCRAFT MODEL DESIGNATION',year:'4 YR MFR',serial:'5 AIRCRAFT SERIAL NO',engineBuilder:'6 ENGINE MANUFACTUREs or BUILDERS NAME',engineModel:'7 ENGINE MODEL DESIGNATION',engineCount:'8 NUMBER OF ENGINES',propBuilder:'9 PROPELLER MANUFACTUREs or BUILDERS NAME',propModel:'10 PROP MODEL',otherCategory:'Other-Standard AW Cert',specialOperations:'Special Purpose Operation(s) (Specify)',retainCertificate:'AW CERT to Retain',retainDate:'DATE or ISSUANCE',ownerName:'NAME',ownerAddress:'ADDRESS',tcds:'AIRCRAFT SPECIFICATION',adSupplement:'AIRWORTHINESS DIRECTIVES (Check if all applicable ADs are complied with and give the number of the last AD SUPPLEMENT available in the biweekly series as of the date of application)',stcs:'SUPPLEMENTAL TYPE CERTIFICATE (List number of each STC incorporated)',hours:'TOTAL AIRFRAME HOURS',experimentalHours:'EXPERIMENTAL ONLY Enter hours flown since last certificate issued or renewed',applicationDate:'3.D DATE OF APPLICATION',inspectorCertificate:'CERTIFICATED MECHANIC Give Certificate No',inspectionDate:'4. Inspection Agency Verification date',inspectorName:'PRINT NAME and TITLE of INSPECTOR as entered in logbook',manufacturer:'NAME_2',manufacturerAddress:'ADDRESS_2',productionNumber:'PRODUCTION CERTIFICATE Give production certificate number',quantity:'C GIVE QUANTITY OF CERTIFICATES REQUIRED FOR OPERATING NEEDS',from:'FROM',to:'TO',via:'VIA',duration:'DURATION',noncompliance:'D THE AIRCRAFT DOES NOT MEET THE APPLICABLE AIRWORTHINESS REQUIREMENTS AS FOLLOWS',restrictions:'E THE FOLLOWING RESTRICTIONS ARE CONSIDERED NECESSARY FOR SAFE OPERATION Use attachment if necessary'};
function safeLatin(value:string){for(const character of value){const code=character.charCodeAt(0);if(code!==9&&code!==10&&code!==13&&(code<32||code>255))throw new Error('The PDF draft cannot preserve one or more non-Latin characters. Your saved form is unchanged.');}return value.replace(/[\r\n]+/g,' ').trim();}
function setText(form:PDFForm,name:string,value:string|undefined){if(!value)return;try{const f=form.getTextField(name);f.setText(safeLatin(value));f.setFontSize(value.length>120?5:value.length>55?6:8);}catch{/* A malformed source widget remains represented in the appendix. */}}
function check(form:PDFForm,key:string){const name=checkboxMap[key];if(!name)return;try{form.getCheckBox(name).check();}catch{/* Some source checkbox widgets are not attached to the canonical field tree. */}}
function wrap(text:string,font:PDFFont,size:number,width:number){const words=safeLatin(text).split(/\s+/);const lines:string[]=[];let line='';for(const w of words){const next=line?`${line} ${w}`:w;if(font.widthOfTextAtSize(next,size)>width&&line){lines.push(line);line=w;}else line=next;}if(line)lines.push(line);return lines;}
export async function buildDraftPdf(data:ApplicationData,documents:DocumentRecord[]){
 const bytes=await fetch('/sources/FAA_Form_8130-6.pdf').then(r=>{if(!r.ok)throw new Error('The source form is unavailable.');return r.arrayBuffer();});const pdf=await PDFDocument.load(bytes,{ignoreEncryption:true});pdf.removePage(0);const form=pdf.getForm();const a=data.answers,f=data.fields;
 const active=new Set(sections(a).map(s=>s.id));
 const keysBySection:Record<string,string[]>={I:['registration','builder','model','year','serial','engineBuilder','engineModel','engineCount','propBuilder','propModel'],II:['otherCategory','specialOperations','retainCertificate','retainDate'],III:['ownerName','ownerAddress','tcds','adSupplement','stcs','hours','experimentalHours'],IV:['inspectorCertificate','inspectionDate','inspectorName'],VI:['manufacturer','manufacturerAddress','productionNumber','quantity'],VII:['from','to','via','duration','noncompliance','restrictions']};
 for(const id of active)for(const key of keysBySection[id]||[])setText(form,textMap[key],f[key]);
 const signer=[f.signerName,f.signerTitle].filter(Boolean).join(', ');
 if(active.has('III')){setText(form,'3.D DATE OF APPLICATION',f.applicationDate);setText(form,'NAME AND TITLE Print or type',signer);}
 if(active.has('VI')){setText(form,'6 Production Flight Testing date',f.applicationDate);setText(form,'NAME AND TITLE Print or type_2',signer);}
 if(active.has('VII')){setText(form,'REGISTERED OWNER',f.ownerName);setText(form,'ADDRESS_3',f.ownerAddress);setText(form,'BUILDER Make',f.builder);setText(form,'MODEL',f.model);setText(form,'SERIAL NUMBER',f.serial);setText(form,'REGISTRATION MARK',f.registration);setText(form,'7.B DEPARTURE DATE',f.departureDate);setText(form,'Special Flight Permit  Date',f.applicationDate);setText(form,'NAME AND TITLE',signer);}
 if(a.family==='standard')check(form,'Standard');else {check(form,'Special');check(form,a.family==='light-sport'?'Light-sport':a.family[0].toUpperCase()+a.family.slice(1));}if(a.family==='multiple'){check(form,'Multiple');check(form,'Restricted');check(form,a.multipleOther);}
 if(a.family==='standard'||(a.family==='multiple'&&a.multipleOther==='Standard'))check(form,a.category==='Other'?'Standard Other':a.category);if(a.family==='provisional')check(form,a.category);if(isFlight(a)){check(form,'Special');check(form,'Special flight permit');check(form,a.category);}a.purposes.forEach(p=>check(form,p==='Other'?'Restricted Other':p));if(f.specialOperations)check(form,'Special operations');if(f.retainCertificate)check(form,'Retain');if(f.dealer==='Yes')check(form,'Dealer');if(isImport(a))check(form,'Import');if(f.tcds)check(form,'TCDS');if(f.adCompliance==='Yes')check(form,'AD');if(f.stcs&&f.stcs!=='N/A')check(form,'STC');if(f.maintenance==='Yes')check(form,'Maintenance');
 const inspectMap:Record<string,string>={'14 CFR part 121 certificate holder':'Check Box67','Certificated mechanic':'Check Box68','Certificated repair station':'Check Box70','Aircraft manufacturer':'Check Box66','Certificated foreign repair station':'Check Box69'};if(f.inspectorType){try{form.getCheckBox(inspectMap[f.inspectorType]).check();}catch{}}
 const productionMap:Record<string,string>={'Production certificate':'Check Box82','Type certificate':'Check Box81','May not meet airworthiness requirements, but capable of safe flight':'Check Box80'};if(f.productionBasis){try{form.getCheckBox(productionMap[f.productionBasis]).check();}catch{}}
 if(a.category==='Customer demonstration flights'){try{form.getCheckBox('Check Box83').check();}catch{}}
 const crew=(f.crew||'').toLowerCase();for(const [term,name] of [['pilot','Check Box84'],['co-pilot','Check Box85'],['flight engineer','Check Box86'],['other','Check Box87']] as const)if(crew.includes(term))try{form.getCheckBox(name).check();}catch{}
 const font=await pdf.embedFont(StandardFonts.Helvetica),bold=await pdf.embedFont(StandardFonts.HelveticaBold);for(const p of pdf.getPages()){p.drawText('CONCEPT DRAFT - NOT SUBMITTED TO THE FAA',{x:72,y:18,size:7,font:bold,color:rgb(.13,.32,.69)});}
 let page=pdf.addPage([612,792]),y=735;const nextPage=()=>{page=pdf.addPage([612,792]);y=735;};const line=(label:string,value:string,source?:string)=>{const lines=wrap(value||'Not provided',font,9,470);if(y<70+lines.length*13)nextPage();page.drawText(label.toUpperCase(),{x:56,y,size:7,font:bold,color:rgb(.36,.45,.58)});y-=14;for(const l of lines){page.drawText(l,{x:56,y,size:9,font,color:rgb(.08,.15,.24)});y-=13;}if(source){page.drawText(source,{x:56,y,size:6.5,font,color:rgb(.42,.49,.59)});y-=13;}y-=8;};
 page.drawText('FORM 8130-6 CONCEPT DRAFT - APPLICANT APPENDIX',{x:56,y,size:16,font:bold,color:rgb(.08,.15,.24)});y-=28;page.drawText('This appendix preserves the complete concept entries. It is not an FAA AWC submission or signature.',{x:56,y,size:8,font,color:rgb(.25,.34,.46)});y-=30;line('Certificate path',`${familyLabel(a)} - ${routeDetail(a)}`,'AC 21-12D, Chapters 2-4');
 for(const s of sections(a)){if(y<110)nextPage();page.drawText(`SECTION ${s.id}  ${s.title.toUpperCase()}`,{x:56,y,size:11,font:bold,color:rgb(.13,.32,.69)});y-=20;for(const field of s.fields)line(field.label,f[field.id]||'',field.hint);}
 line('Intended FAA office',f.faaOffice||'');line('Requested designee',f.designee||'');if(y<150)nextPage();page.drawText('DOCUMENT INVENTORY',{x:56,y,size:11,font:bold,color:rgb(.13,.32,.69)});y-=20;const reqs=requirements(a);for(const d of documents){line(reqs.find(r=>r.id===d.requirementId)?.title||'Earlier-path document',`${d.name} (${d.size} bytes)`);}
 page.drawText('Applicant certification and concept consent were recorded in the workspace. Official Form 8130-6 signature fields remain blank.',{x:56,y:35,size:7,font,color:rgb(.25,.34,.46)});
 form.updateFieldAppearances(font);form.flatten();const saved=await pdf.save();const copy=new Uint8Array(saved.length);copy.set(saved);return new Blob([copy.buffer],{type:'application/pdf'});
}
export function savePdf(blob:Blob){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='FAA-Form-8130-6-concept-draft.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
